[build-system]
requires = ["setuptools>=61.0", "wheel", "build"]
build-backend = "setuptools.build_meta"

[project]
name = "minivalidator"
version = "0.1.0"
description = "Pequeña librería de validadores reutilizables."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [{name="Tu Nombre", email="tu-email@example.com"}]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
dependencies = []
